begin;

create schema if not exists extensions;
create extension if not exists "uuid-ossp" with schema extensions;

create table if not exists public.accounts (
  id uuid primary key default extensions.uuid_generate_v4(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  twitch_id text unique,
  channel text,
  user_id uuid references auth.users(id) on delete cascade
);

create table if not exists public.active_pokes (
  id uuid primary key default extensions.uuid_generate_v4(),
  channel text not null unique,
  poke text not null,
  health smallint not null default 50,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.collections (
  id uuid primary key default extensions.uuid_generate_v4(),
  "user" text not null,
  channel text not null,
  poke text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trades (
  id uuid primary key default extensions.uuid_generate_v4(),
  "user" text,
  poke text,
  pokeid text,
  recipient text,
  recipientpoke text,
  recipientpokeid text,
  created_at timestamptz default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  provider_id text := nullif(trim(new.raw_user_meta_data->>'provider_id'), '');
  channel_name text := nullif(trim(new.raw_user_meta_data->>'name'), '');
begin
  if coalesce(new.raw_app_meta_data->>'provider', '') <> 'twitch' then
    raise exception 'Only Twitch identities are supported';
  end if;

  if provider_id is null or channel_name is null then
    raise exception 'Twitch identity metadata is incomplete';
  end if;

  insert into public.accounts (user_id, twitch_id, channel)
  values (new.id, provider_id, lower(channel_name))
  on conflict (twitch_id) do update
  set
    channel = excluded.channel,
    updated_at = now()
  where public.accounts.user_id = excluded.user_id;

  if not found then
    raise exception 'Twitch identity is already linked';
  end if;

  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'on_auth_user_created'
  ) then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute function public.handle_new_user();
  end if;
end;
$$;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.migration_rejects (
  id bigint generated by default as identity primary key,
  source_table text not null,
  source_id text,
  reason text not null,
  payload jsonb not null,
  rejected_at timestamptz not null default now()
);

with rejected as (
  delete from public.trades as t
  where
    t.pokeid is null
    or t.recipientpokeid is null
    or not exists (
      select 1 from public.collections c where c.id::text = t.pokeid
    )
    or not exists (
      select 1 from public.collections c where c.id::text = t.recipientpokeid
    )
  returning t.*
)
insert into private.migration_rejects (
  source_table,
  source_id,
  reason,
  payload
)
select
  'public.trades',
  rejected.id::text,
  'Trade references a missing or invalid collection row',
  to_jsonb(rejected)
from rejected;

alter table public.trades
  alter column pokeid type uuid using pokeid::uuid,
  alter column recipientpokeid type uuid using recipientpokeid::uuid;

alter table public.trades
  alter column "user" set not null,
  alter column poke set not null,
  alter column pokeid set not null,
  alter column recipient set not null,
  alter column recipientpoke set not null,
  alter column recipientpokeid set not null;

update public.trades
set created_at = now()
where created_at is null;

alter table public.trades
  alter column created_at set default now(),
  alter column created_at set not null;

alter table public.trades
  add constraint trades_pokeid_fkey
    foreign key (pokeid) references public.collections(id) on delete cascade,
  add constraint trades_recipientpokeid_fkey
    foreign key (recipientpokeid) references public.collections(id) on delete cascade;

create unique index if not exists accounts_user_id_key
  on public.accounts(user_id);
create unique index if not exists accounts_channel_key
  on public.accounts(channel);
create index if not exists collections_user_poke_idx
  on public.collections("user", poke);
create index if not exists collections_channel_created_at_idx
  on public.collections(channel, created_at desc);
create index if not exists collections_poke_created_at_idx
  on public.collections(poke, created_at desc);
create unique index if not exists trades_open_offered_collection_key
  on public.trades(pokeid);
create index if not exists trades_recipient_created_at_idx
  on public.trades(recipient, created_at desc);

alter table public.active_pokes enable row level security;
alter table public.collections enable row level security;
alter table public.trades enable row level security;

drop policy if exists "Public can read active pokes" on public.active_pokes;
create policy "Public can read active pokes"
on public.active_pokes for select
to anon, authenticated
using (true);

drop policy if exists "Public can read collections" on public.collections;
create policy "Public can read collections"
on public.collections for select
to anon, authenticated
using (true);

drop policy if exists "Trade participants can read offers" on public.trades;
create policy "Trade participants can read offers"
on public.trades for select
to authenticated
using (
  user = (
    select a.channel
    from public.accounts a
    where a.user_id = (select auth.uid())
  )
  or recipient = (
    select a.channel
    from public.accounts a
    where a.user_id = (select auth.uid())
  )
);

create or replace function public.gift_pokemon(
  p_collection_id uuid,
  p_recipient text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  actor_channel text;
  owned_row public.collections%rowtype;
begin
  select channel into actor_channel
  from public.accounts
  where user_id = auth.uid();

  if actor_channel is null then
    raise exception 'Authentication required';
  end if;

  if nullif(trim(p_recipient), '') is null or lower(p_recipient) = lower(actor_channel) then
    raise exception 'Invalid gift recipient';
  end if;

  if not exists (
    select 1
    from public.collections
    where lower("user") = lower(trim(p_recipient))
  ) then
    raise exception 'Gift recipient was not found';
  end if;

  select * into owned_row
  from public.collections
  where id = p_collection_id and lower("user") = lower(actor_channel)
  for update;

  if not found then
    raise exception 'Pokémon is not owned by the current user';
  end if;

  delete from public.trades
  where pokeid = p_collection_id or recipientpokeid = p_collection_id;

  update public.collections
  set
    "user" = lower(trim(p_recipient)),
    channel = actor_channel,
    updated_at = now()
  where id = p_collection_id;
end;
$$;

create or replace function public.create_trade_offer(
  p_offered_collection_id uuid,
  p_requested_collection_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  actor_channel text;
  offered public.collections%rowtype;
  requested public.collections%rowtype;
  new_trade_id uuid;
begin
  select channel into actor_channel
  from public.accounts
  where user_id = auth.uid();

  if actor_channel is null then
    raise exception 'Authentication required';
  end if;

  select * into offered
  from public.collections
  where id = p_offered_collection_id and lower("user") = lower(actor_channel)
  for update;

  if not found then
    raise exception 'Offered Pokémon is not owned by the current user';
  end if;

  select * into requested
  from public.collections
  where id = p_requested_collection_id
    and lower("user") <> lower(actor_channel)
  for update;

  if not found then
    raise exception 'Requested Pokémon is unavailable';
  end if;

  insert into public.trades (
    "user", poke, pokeid, recipient, recipientpoke, recipientpokeid
  )
  values (
    actor_channel,
    offered.poke,
    offered.id,
    requested."user",
    requested.poke,
    requested.id
  )
  returning id into new_trade_id;

  return new_trade_id;
end;
$$;

create or replace function public.resolve_trade_offer(
  p_trade_id uuid,
  p_decision text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  actor_channel text;
  trade_row public.trades%rowtype;
  offered public.collections%rowtype;
  requested public.collections%rowtype;
begin
  select channel into actor_channel
  from public.accounts
  where user_id = auth.uid();

  if actor_channel is null then
    raise exception 'Authentication required';
  end if;

  select * into trade_row
  from public.trades
  where id = p_trade_id
  for update;

  if not found then
    raise exception 'Trade offer not found';
  end if;

  if p_decision = 'cancel' then
    if lower(trade_row."user") <> lower(actor_channel) then
      raise exception 'Only the sender can cancel this offer';
    end if;
    delete from public.trades where id = p_trade_id;
    return;
  end if;

  if lower(trade_row.recipient) <> lower(actor_channel) then
    raise exception 'Only the recipient can resolve this offer';
  end if;

  if p_decision = 'deny' then
    delete from public.trades where id = p_trade_id;
    return;
  end if;

  if p_decision <> 'accept' then
    raise exception 'Invalid trade decision';
  end if;

  select * into offered
  from public.collections
  where id = trade_row.pokeid
    and lower("user") = lower(trade_row."user")
  for update;

  select * into requested
  from public.collections
  where id = trade_row.recipientpokeid
    and lower("user") = lower(trade_row.recipient)
  for update;

  if offered.id is null or requested.id is null then
    raise exception 'One of the Pokémon is no longer available';
  end if;

  update public.collections
  set
    "user" = trade_row.recipient,
    channel = trade_row."user",
    updated_at = now()
  where id = offered.id;

  update public.collections
  set
    "user" = trade_row."user",
    channel = trade_row.recipient,
    updated_at = now()
  where id = requested.id;

  delete from public.trades
  where id = p_trade_id
    or pokeid in (offered.id, requested.id)
    or recipientpokeid in (offered.id, requested.id);
end;
$$;

revoke all on function public.gift_pokemon(uuid, text) from public, anon;
revoke all on function public.create_trade_offer(uuid, uuid) from public, anon;
revoke all on function public.resolve_trade_offer(uuid, text) from public, anon;
grant execute on function public.gift_pokemon(uuid, text) to authenticated;
grant execute on function public.create_trade_offer(uuid, uuid) to authenticated;
grant execute on function public.resolve_trade_offer(uuid, text) to authenticated;

revoke execute on function public.handle_new_user() from public, anon, authenticated;

drop policy if exists "Users can insert their own profile." on public.accounts;
drop policy if exists "Users can insert their own accounts." on public.accounts;
create policy "Users can insert their own account"
on public.accounts for insert
to authenticated
with check ((select auth.uid()) = user_id);

commit;
